### ISSUE TITLE
Renders not having video

### ISSUE THREAD

**Issue by FifthWit** [NeKzor/autorender#2]
**Describe the bug**
Certain demos have an empty src="" value for the mp4 file to watch the video, examples:
https://autorender.p2sr.org/videos/9ZOfXc485Os Has a value thus you can watch,
https://autorender.p2sr.org/videos/JulXODXUD5g has no value so you cannot watch/ 

**To Reproduce**
1.  above

**Expected behavior**
That it loads

**Desktop/Smartphone Information**
 - OS: Windows 11 Home
 - Browser: Firefox
 - Version: most recent

**Comment by NeKzor** [comment]
We missed a few renders from `2024-09-09` to `2024-09-12`. Most likely related that the CDN did not warn me that I had to charge it again. It should not happen again for like year. I need to figure out how to get an alert somehow. Also I'll make sure to trigger a rerender on all those videos when I have time.

**Comment by FifthWit** [comment]
Oh alright thanks for the reply NeKz, how everything works fine

**Comment by NeKzor** [comment]
Opening this issue again because this is still not fixed.

**Comment by NeKzor** [comment]
Uploaded all 108 videos. I also made sure that my alerts are going to the correct inbox where I have notifications enabled.
